[package]
name = "h3cellstorepy"
version = "0.9.0"
edition = "2021"
authors = [
    "Nico Mandery <nico.mandery@dlr.de>"
]

[lib]
name = "h3cellstorepy"
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1"

[dependencies.h3cellstore]
path =  "../h3cellstore"
features = [
    "export",
    "tls"
]

[dependencies.pyo3]
version = "^0.16"
features = [
    "extension-module",
    "multiple-pymethods",
    "abi3",
    # minimum python version this library supports
    # as this library depends on pandas>=1.2 we are using the
    # same minimum python version as pandas.
    # https://pypi.org/project/pandas/1.2.3/
    "abi3-py37"
]

[dependencies.tracing-subscriber]
version = "0.3"
features = [
    #"json",
    "env-filter"
]

[dependencies.tokio]
version = "^1"
default-features = false
features = [
    "io-util",
    "time",
    "net",
    "sync",
    "rt-multi-thread",
    "macros",
]


[package.metadata.maturin]
requires-dist = [
    "loguru>=0.5"
]
