[package]
name = "h3cellstorepy"
version = "0.9.0"
edition = "2021"
authors = [
    "Nico Mandery <nico.mandery@dlr.de>"
]

[lib]
name = "h3cellstorepy"
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1"
serde_json = "1"
lazy_static = "1"
regex = "1.5.5"
py_geo_interface = "0.1.1"
geo-types = "0.7"
numpy = "0.16"

[dependencies.h3cellstore]
path =  "../h3cellstore"
features = [
    "export",
    "tls",
    "serde"
]

[dependencies.pyo3]
version = "^0.16"
features = [
    "extension-module",
    "multiple-pymethods",
    "abi3",
    # minimum python version this library supports
    "abi3-py37"
]

[dependencies.tracing-subscriber]
version = "0.3"
features = [
    #"json",
    "env-filter"
]

[dependencies.tokio]
version = "^1"
default-features = false
features = [
    "io-util",
    "time",
    "net",
    "sync",
    "rt-multi-thread",
    "macros",
]


[package.metadata.maturin]
requires-dist = [
    "loguru>=0.5",
    "h3>=3.7.4",
    "geojson",
    "numpy"
]
