[package]
name = "h3cpy"
version = "0.1.0"
edition = "2018"
authors = [
    "Nico Mandery <nico.mandery@dlr.de>"
]

[lib]
name = "h3cpy"
crate-type = ["cdylib"]

[dependencies]
h3cpy_int = { path = "../h3cpy_int" }
numpy = "^0.12"
geo-types = "^0.6"

[dependencies.geojson]
version = "^0.21"
features = [
    "geo-types"
]

[dependencies.h3]
git = "https://github.com/nmandery/h3r"
tag = "v0.3.3"
features = ["with-geo-types-0_6"]
default_features = false

[dependencies.h3-sys]
git = "https://github.com/nmandery/h3r"
tag = "v0.3.3"

[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]

[package.metadata.maturin]
requires-dist = [
    "numpy",
    "pandas>=1.1"
]