[package]
name = "h3cpy"
version = "0.1.0"
edition = "2018"
authors = [
    "Nico Mandery <nico.mandery@dlr.de>"
]

[lib]
name = "h3cpy"
crate-type = ["cdylib"]

[dependencies]
h3cpy_int = { path = "../h3cpy_int" }
numpy = "0.12"
geo-types = "^0.6"
geo = "^0.16"
itertools = "0.10"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
chrono-tz = "0.5"

[dependencies.geojson]
version = "^0.21"
features = [
    "geo-types"
]

[dependencies.h3ron]
git = "https://github.com/nmandery/h3ron.git"
tag = "v0.4.1"

[dependencies.h3ron-h3-sys]
git = "https://github.com/nmandery/h3ron.git"
tag = "v0.4.1"

[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]

[dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["io-util", "time", "net", "sync", "rt-threaded"]

[dependencies.futures-util]
version = "0.3.5"
features = ["sink"]

[dependencies.clickhouse-rs]
git = "https://github.com/suharev7/clickhouse-rs.git"
rev = "d288a4f8a" # to include https://github.com/suharev7/clickhouse-rs/pull/102

[package.metadata.maturin]
requires-dist = [
    "numpy",
    "pandas>=1.1",
    "geojson>=2.5"
]