[package]
name = "h3cpy_int"
version = "0.1.0"
authors = ["Nico Mandery <nico.mandery@dlr.de>"]
edition = "2018"
description = "Internal code of h3cpy"

[dependencies]
regex = "^1.4"
lazy_static = "1.4.0"
geo-types = "^0.6"
geo = "^0.16"

[dependencies.h3ron]
git = "https://github.com/nmandery/h3ron.git"
tag = "v0.4.1"

[dependencies.h3ron-h3-sys]
git = "https://github.com/nmandery/h3ron.git"
tag = "v0.4.1"

[dependencies.clickhouse-rs]
git = "https://github.com/suharev7/clickhouse-rs.git"
rev = "d288a4f8a" # to include https://github.com/suharev7/clickhouse-rs/pull/102

#[dependencies.tokio]
#version = "0.2.0"
#default-features = false
#features = ["io-util", "time", "net", "sync", "rt-threaded"]