[build-system]
requires = [
    "maturin>=0.10.2,<0.11",
    "pytest==6.2",
    "pytest-benchmark==3.4"
]
build-backend = "maturin"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules"
testpaths = [
    "bamboo_h3",
    "tests"
]
